# Generated by Django 4.2 on 2023-07-29 15:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoIncrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oghab101', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1019999)])),
                ('oghab102', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1029999)])),
                ('oghab103', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1039999)])),
                ('oghab104', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1049999)])),
                ('oghab105', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1059999)])),
                ('oghab106', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1069999)])),
                ('oghab107', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1079999)])),
            ],
        ),
        migrations.CreateModel(
            name='AutoIncrementCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oghab101', models.BigIntegerField(blank=True, null=True)),
                ('oghab102', models.BigIntegerField(blank=True, null=True)),
                ('oghab103', models.BigIntegerField(blank=True, null=True)),
                ('oghab104', models.BigIntegerField(blank=True, null=True)),
                ('oghab105', models.BigIntegerField(blank=True, null=True)),
                ('oghab106', models.BigIntegerField(blank=True, null=True)),
                ('oghab107', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutoIncrementFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemID_01', models.BigIntegerField(blank=True, null=True)),
                ('systemID_02', models.BigIntegerField(blank=True, null=True)),
                ('systemID_03', models.BigIntegerField(blank=True, null=True)),
                ('systemID_04', models.BigIntegerField(blank=True, null=True)),
                ('systemID_05', models.BigIntegerField(blank=True, null=True)),
                ('systemID_06', models.BigIntegerField(blank=True, null=True)),
                ('systemID_07', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('scale', models.CharField(blank=True, max_length=50, null=True)),
                ('inventory', models.CharField(blank=True, max_length=50, null=True)),
                ('operator', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('input', models.BigIntegerField(blank=True, null=True)),
                ('output', models.BigIntegerField(blank=True, null=True)),
                ('left_stock', models.BigIntegerField(blank=True, default=False, null=True)),
                ('document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('document_code', models.CharField(blank=True, max_length=50, null=True)),
                ('recycle_status', models.CharField(blank=True, max_length=50, null=True)),
                ('recycle_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('count', models.BigIntegerField(blank=True, null=True)),
                ('yearly_handling', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Handling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhouse.product')),
            ],
        ),
        migrations.CreateModel(
            name='AllProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumable', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('input', models.FloatField(blank=True, null=True)),
                ('output', models.FloatField(blank=True, null=True)),
                ('afterOperator', models.FloatField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=50, null=True)),
                ('scale', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('buyer', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver', models.CharField(blank=True, max_length=50, null=True)),
                ('document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('document_code', models.CharField(blank=True, max_length=50, null=True)),
                ('factor', models.TextField(blank=True, null=True)),
                ('checkBill', models.TextField(blank=True, null=True)),
                ('amendment', models.TextField(blank=True, null=True)),
                ('obsolete', models.BooleanField(blank=True, null=True)),
                ('systemID', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhouse.product')),
            ],
        ),
    ]
