# Generated by Django 4.2 on 2023-05-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('number_in_out', models.BigIntegerField()),
                ('consumable', models.CharField(blank=True, max_length=50, null=True)),
                ('inventory', models.CharField(blank=True, max_length=50, null=True)),
                ('input', models.BigIntegerField()),
                ('output', models.BigIntegerField()),
                ('operator', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('buyer', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver', models.CharField(blank=True, max_length=50, null=True)),
                ('left_stock', models.BigIntegerField(blank=True, default=False, null=True)),
                ('document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('document_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('recycle_status', models.CharField(blank=True, max_length=50, null=True)),
                ('recycle_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
