# Generated by Django 4.2.3 on 2023-08-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
