# Generated by Django 4.2 on 2023-05-25 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='input',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_in_out',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='output',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AllProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumable', models.CharField(blank=True, max_length=50, null=True)),
                ('inventory', models.CharField(blank=True, max_length=50, null=True)),
                ('input', models.BigIntegerField(blank=True, null=True)),
                ('output', models.BigIntegerField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=50, null=True)),
                ('scale', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('buyer', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver', models.CharField(blank=True, max_length=50, null=True)),
                ('document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('document_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhouse.product')),
            ],
        ),
    ]
