# Generated by Django 4.2.7 on 2024-02-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0002_alter_category_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='value',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='مقدار'),
        ),
    ]
