# Generated by Django 4.2 on 2023-05-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0002_alter_product_date_alter_product_input_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allproducts',
            old_name='inventory',
            new_name='inventory_dst',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='buyer',
            new_name='scale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='input',
        ),
        migrations.RemoveField(
            model_name='product',
            name='output',
        ),
        migrations.RemoveField(
            model_name='product',
            name='receiver',
        ),
    ]
