# Generated by Django 4.2.3 on 2023-08-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0002_alter_allproducts_name_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='seller',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
