# Generated by Django 4.2 on 2023-05-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0003_rename_inventory_allproducts_inventory_dst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='input',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='output',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
