# Generated by Django 4.2 on 2023-08-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0004_alter_allproducts_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='factor',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
