# Generated by Django 4.2 on 2023-05-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0006_autoincrement'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='checkBill',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allproducts',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
