# Generated by Django 4.2.4 on 2023-09-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0006_alter_allproducts_factor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allproducts',
            options={'verbose_name_plural': 'گزارش کالا ها'},
        ),
        migrations.AlterModelOptions(
            name='autoincrement',
            options={'verbose_name_plural': 'شمارنده کد ثبت'},
        ),
        migrations.AlterModelOptions(
            name='autoincrementcheck',
            options={'verbose_name_plural': 'شمارنده کد حواله'},
        ),
        migrations.AlterModelOptions(
            name='autoincrementfactor',
            options={'verbose_name_plural': 'شمارنده کد فاکتور'},
        ),
        migrations.AlterModelOptions(
            name='handling',
            options={'verbose_name_plural': 'انبارداری'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'کالا ها'},
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='handling',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='recycle_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
