# Generated by Django 4.2 on 2023-05-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0007_allproducts_checkbill_allproducts_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
