# Generated by Django 4.2.4 on 2023-09-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0007_alter_allproducts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='factor',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
