# Generated by Django 4.2 on 2023-05-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0008_allproducts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
