# Generated by Django 4.2.4 on 2023-09-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0008_alter_allproducts_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
