# Generated by Django 4.2.4 on 2023-10-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0009_alter_allproducts_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoIncrementProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increment', models.BigIntegerField(blank=True, null=True)),
                ('inventory', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'شمارنده کد ثبت',
            },
        ),
        migrations.CreateModel(
            name='AutoIncrementProductFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increment', models.BigIntegerField(blank=True, null=True)),
                ('inventory', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'شمارنده کد فاکتور',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'گروه',
            },
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'مورد مصرف',
            },
        ),
        migrations.CreateModel(
            name='FactorsProduct',
            fields=[
                ('code', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('inventory', models.CharField(blank=True, max_length=50, null=True)),
                ('factor', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name_plural': 'فاکتور ها',
            },
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='amendment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='buyer',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='checkBill',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='consumable',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='date',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='document_code',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='document_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='factor',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='operator',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='receiver',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='scale',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='seller',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='systemID',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
