# Generated by Django 4.2 on 2023-05-30 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0010_allproducts_afteroperator_allproducts_beforeoperator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allproducts',
            name='beforeOperator',
        ),
    ]
