# Generated by Django 4.2.4 on 2023-10-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0011_autoincrementproductcheck_productcheck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capsule', models.JSONField()),
                ('sender', models.CharField(max_length=50)),
                ('receiver', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'انت',
            },
        ),
    ]
