# Generated by Django 4.2 on 2023-06-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0012_allproducts_amendment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='obsolete',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
