# Generated by Django 4.2.4 on 2023-10-14 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0012_transmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transmission',
            options={'verbose_name_plural': 'انتقالی ها'},
        ),
    ]
