# Generated by Django 4.2.4 on 2023-10-25 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0013_alter_transmission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allproducts',
            options={'verbose_name_plural': 'گزارش کالا'},
        ),
        migrations.AlterModelOptions(
            name='handling',
            options={'verbose_name_plural': 'انبارگردانی'},
        ),
        migrations.AlterModelOptions(
            name='productcheck',
            options={'verbose_name_plural': 'حواله ها'},
        ),
        migrations.RemoveField(
            model_name='allproducts',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transmission',
            name='capsule',
        ),
        migrations.AddField(
            model_name='allproducts',
            name='checkCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warhouse.productcheck'),
        ),
        migrations.AddField(
            model_name='allproducts',
            name='factorCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warhouse.factorsproduct'),
        ),
        migrations.AddField(
            model_name='factorsproduct',
            name='jsonData',
            field=models.JSONField(null=True, verbose_name='کپسول اقلام فاکتور'),
        ),
        migrations.AddField(
            model_name='productcheck',
            name='jsonData',
            field=models.JSONField(null=True, verbose_name='کپسول اقلام حواله'),
        ),
        migrations.AddField(
            model_name='transmission',
            name='category',
            field=models.CharField(default='', max_length=50, verbose_name='گروه'),
        ),
        migrations.AddField(
            model_name='transmission',
            name='date',
            field=models.CharField(default='', max_length=50, verbose_name='تاریخ'),
        ),
        migrations.AddField(
            model_name='transmission',
            name='input',
            field=models.FloatField(blank=True, null=True, verbose_name='تعداد'),
        ),
        migrations.AddField(
            model_name='transmission',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='نام کالا'),
        ),
        migrations.AddField(
            model_name='transmission',
            name='scale',
            field=models.CharField(default='', max_length=50, verbose_name='مقیاس'),
        ),
        migrations.AddField(
            model_name='transmission',
            name='systemID',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='شماره ثبت سیستم'),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='afterOperator',
            field=models.FloatField(blank=True, null=True, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='amendment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='اصلاحیه'),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='buyer',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='خریدار'),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='checkBill',
            field=models.TextField(blank=True, null=True, verbose_name='حواله'),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='consumable',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='مورد مصرف'),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='date',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='document_code',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='شناسه مدرک'),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='document_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='نوع مدرک'),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='factor',
            field=models.TextField(blank=True, default='فاکتور', null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='input',
            field=models.FloatField(blank=True, null=True, verbose_name='ورودی'),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='obsolete',
            field=models.BooleanField(blank=True, null=True, verbose_name='باطل کردن'),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='operator',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='عملیات'),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='output',
            field=models.FloatField(blank=True, null=True, verbose_name='حروجی'),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhouse.product', verbose_name='کالای مربوط به'),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='receiver',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='تحویل گیرنده'),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='scale',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='مقیاس'),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='seller',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='فروشنده'),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='systemID',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='شماره سیستم'),
        ),
        migrations.AlterField(
            model_name='autoincrementproduct',
            name='increment',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='شمارنده'),
        ),
        migrations.AlterField(
            model_name='autoincrementproduct',
            name='inventory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='انبار'),
        ),
        migrations.AlterField(
            model_name='autoincrementproductcheck',
            name='increment',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='شمارنده'),
        ),
        migrations.AlterField(
            model_name='autoincrementproductcheck',
            name='inventory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='انبار'),
        ),
        migrations.AlterField(
            model_name='autoincrementproductfactor',
            name='increment',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='شمارنده'),
        ),
        migrations.AlterField(
            model_name='autoincrementproductfactor',
            name='inventory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='انبار'),
        ),
        migrations.AlterField(
            model_name='category',
            name='value',
            field=models.CharField(blank=True, max_length=50, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='value',
            field=models.CharField(blank=True, max_length=50, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='factorsproduct',
            name='code',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد ثبت'),
        ),
        migrations.AlterField(
            model_name='factorsproduct',
            name='factor',
            field=models.TextField(blank=True, default='', null=True, verbose_name='فایل باینری فاکتور'),
        ),
        migrations.AlterField(
            model_name='factorsproduct',
            name='inventory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='انبار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='گروه کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد ثبت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='مقدار رویت شده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='توضیحت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه مدرک'),
        ),
        migrations.AlterField(
            model_name='product',
            name='document_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع مدرک'),
        ),
        migrations.AlterField(
            model_name='product',
            name='input',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ورودی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='انبار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='left_stock',
            field=models.BigIntegerField(blank=True, default=False, null=True, verbose_name='مانده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='نام کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='operator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عملیات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='output',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='خروجی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recycle_date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ آخرین انبار گردانی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recycle_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='وضعیت انبارگردانی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='scale',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مقیاس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='yearly_handling',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='سال انبارگردانی'),
        ),
        migrations.AlterField(
            model_name='productcheck',
            name='checks',
            field=models.TextField(blank=True, default='', null=True, verbose_name='فایل باینری حواله'),
        ),
        migrations.AlterField(
            model_name='productcheck',
            name='code',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد ثبت'),
        ),
        migrations.AlterField(
            model_name='productcheck',
            name='inventory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='انبار'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='receiver',
            field=models.CharField(max_length=50, verbose_name='دریافت کننده'),
        ),
        migrations.AlterField(
            model_name='transmission',
            name='sender',
            field=models.CharField(max_length=50, verbose_name='ارسال کننده'),
        ),
    ]
