# Generated by Django 4.2.7 on 2024-01-30 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0014_alter_allproducts_options_alter_handling_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoIncrement',
        ),
        migrations.DeleteModel(
            name='AutoIncrementCheck',
        ),
        migrations.DeleteModel(
            name='AutoIncrementFactor',
        ),
        migrations.RemoveField(
            model_name='allproducts',
            name='checkBill',
        ),
        migrations.RemoveField(
            model_name='allproducts',
            name='factor',
        ),
        migrations.RemoveField(
            model_name='allproducts',
            name='scale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='document_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='input',
        ),
        migrations.RemoveField(
            model_name='product',
            name='left_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='product',
            name='output',
        ),
    ]
