# Generated by Django 4.2 on 2023-06-03 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0014_remove_product_obsolete_allproducts_obsolete'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumable', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('input', models.BigIntegerField(blank=True, null=True)),
                ('output', models.BigIntegerField(blank=True, null=True)),
                ('afterOperator', models.BigIntegerField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=50, null=True)),
                ('scale', models.CharField(blank=True, max_length=50, null=True)),
                ('inventory_dst', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('buyer', models.CharField(blank=True, max_length=50, null=True)),
                ('receiver', models.CharField(blank=True, max_length=50, null=True)),
                ('document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('document_code', models.CharField(blank=True, max_length=50, null=True)),
                ('factor', models.TextField(blank=True, null=True)),
                ('checkBill', models.TextField(blank=True, null=True)),
                ('amendment', models.TextField(blank=True, null=True)),
                ('obsolete', models.BooleanField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warhouse.product')),
            ],
        ),
    ]
