# Generated by Django 4.2 on 2023-06-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0015_pendingproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingproducts',
            name='inventory_src',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
