# Generated by Django 4.2 on 2023-06-03 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0016_pendingproducts_inventory_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingproducts',
            name='afterOperator',
        ),
        migrations.RemoveField(
            model_name='pendingproducts',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='pendingproducts',
            name='consumable',
        ),
        migrations.RemoveField(
            model_name='pendingproducts',
            name='obsolete',
        ),
        migrations.RemoveField(
            model_name='pendingproducts',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='pendingproducts',
            name='output',
        ),
        migrations.RemoveField(
            model_name='pendingproducts',
            name='product',
        ),
    ]
