# Generated by Django 4.2 on 2023-06-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0017_remove_pendingproducts_afteroperator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingproducts',
            name='obsolete',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
