# Generated by Django 4.2 on 2023-06-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0018_pendingproducts_obsolete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingproducts',
            old_name='obsolete',
            new_name='agree',
        ),
        migrations.AddField(
            model_name='pendingproducts',
            name='disagree',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
