# Generated by Django 4.2 on 2023-06-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0019_rename_obsolete_pendingproducts_agree_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingProducts',
        ),
        migrations.RemoveField(
            model_name='allproducts',
            name='inventory_dst',
        ),
    ]
