# Generated by Django 4.2 on 2023-06-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0021_autoincrementproperty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoIncrementProperty',
        ),
    ]
