# Generated by Django 4.2 on 2023-06-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0022_delete_autoincrementproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoincrement',
            name='oghab101',
            field=models.BigIntegerField(blank=True, max_length=1019999, null=True),
        ),
        migrations.AlterField(
            model_name='autoincrement',
            name='oghab102',
            field=models.BigIntegerField(blank=True, max_length=1029999, null=True),
        ),
        migrations.AlterField(
            model_name='autoincrement',
            name='oghab103',
            field=models.BigIntegerField(blank=True, max_length=1039999, null=True),
        ),
        migrations.AlterField(
            model_name='autoincrement',
            name='oghab104',
            field=models.BigIntegerField(blank=True, max_length=1049999, null=True),
        ),
        migrations.AlterField(
            model_name='autoincrement',
            name='oghab105',
            field=models.BigIntegerField(blank=True, max_length=1059999, null=True),
        ),
        migrations.AlterField(
            model_name='autoincrement',
            name='oghab106',
            field=models.BigIntegerField(blank=True, max_length=1069999, null=True),
        ),
        migrations.AlterField(
            model_name='autoincrement',
            name='oghab107',
            field=models.BigIntegerField(blank=True, max_length=1079999, null=True),
        ),
    ]
