# Generated by Django 4.2 on 2023-06-07 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0023_alter_autoincrement_oghab101_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoincrement',
            name='oghab101',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1019999)]),
        ),
        migrations.AlterField(
            model_name='autoincrement',
            name='oghab102',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1029999)]),
        ),
        migrations.AlterField(
            model_name='autoincrement',
            name='oghab103',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1039999)]),
        ),
        migrations.AlterField(
            model_name='autoincrement',
            name='oghab104',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1049999)]),
        ),
        migrations.AlterField(
            model_name='autoincrement',
            name='oghab105',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1059999)]),
        ),
        migrations.AlterField(
            model_name='autoincrement',
            name='oghab106',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1069999)]),
        ),
        migrations.AlterField(
            model_name='autoincrement',
            name='oghab107',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1079999)]),
        ),
    ]
