# Generated by Django 4.2 on 2023-06-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0024_alter_autoincrement_oghab101_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
