# Generated by Django 4.2 on 2023-06-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0025_allproducts_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allproducts',
            name='count',
        ),
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
