# Generated by Django 4.2 on 2023-06-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0027_handling'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='yearly_handling',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
