# Generated by Django 4.2 on 2023-06-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0030_alter_product_yearly_handling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='afterOperator',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='input',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allproducts',
            name='output',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
