# Generated by Django 4.2.1 on 2023-07-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0031_alter_allproducts_afteroperator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoIncrementCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oghab101', models.BigIntegerField(blank=True, null=True)),
                ('oghab102', models.BigIntegerField(blank=True, null=True)),
                ('oghab103', models.BigIntegerField(blank=True, null=True)),
                ('oghab104', models.BigIntegerField(blank=True, null=True)),
                ('oghab105', models.BigIntegerField(blank=True, null=True)),
                ('oghab106', models.BigIntegerField(blank=True, null=True)),
                ('oghab107', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
