# Generated by Django 4.2.1 on 2023-07-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0032_autoincrementcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoIncrementFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemID', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
