# Generated by Django 4.2.1 on 2023-07-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0033_autoincrementfactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
