# Generated by Django 4.2.1 on 2023-07-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0034_allproducts_systemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='systemID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
