# Generated by Django 4.2.1 on 2023-07-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0035_alter_allproducts_systemid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoincrementfactor',
            old_name='systemID',
            new_name='systemID_01',
        ),
        migrations.AddField(
            model_name='autoincrementfactor',
            name='systemID_02',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoincrementfactor',
            name='systemID_03',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoincrementfactor',
            name='systemID_04',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoincrementfactor',
            name='systemID_05',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoincrementfactor',
            name='systemID_06',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoincrementfactor',
            name='systemID_07',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
