# Generated by Django 4.2.7 on 2024-02-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractNumber', models.CharField(blank=True, max_length=500, null=True, verbose_name='شماره قرارداد')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام')),
                ('office', models.CharField(blank=True, max_length=50, null=True, verbose_name='محل کار')),
                ('type_form', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع فرم')),
                ('dateContract', models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ قرارداد')),
                ('contractPrice', models.CharField(blank=True, max_length=50, null=True, verbose_name='مبلغ قرارداد')),
                ('durationContract', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدت قرارداد')),
                ('prePaidPrice', models.CharField(blank=True, max_length=50, null=True, verbose_name='مبلغ پیش پرداخت')),
                ('goodPrice', models.CharField(blank=True, max_length=50, null=True, verbose_name='مبلغ حسن انجام کار')),
                ('typeBail1', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع ضمانت')),
                ('firstBail', models.CharField(blank=True, max_length=50, null=True, verbose_name='مشخصه ضمانت')),
                ('secondBail', models.CharField(blank=True, max_length=50, null=True, verbose_name='مشخصه ضمانت')),
                ('commitmentPrice', models.CharField(blank=True, max_length=50, null=True, verbose_name='مبلغ تعهد انجام کار')),
                ('typeBail2', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع ضمانت')),
                ('firstBail2', models.CharField(blank=True, max_length=50, null=True, verbose_name='مشخصه ضمانت')),
                ('secondBail2', models.CharField(blank=True, max_length=50, null=True, verbose_name='مشخصه ضمانت')),
                ('topicContract', models.CharField(blank=True, max_length=50, null=True, verbose_name='موضوع قرارداد')),
                ('typeContract', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع قرارداد')),
                ('clearedDate', models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ تسویه')),
                ('receivedDocument', models.BooleanField(blank=True, default=False, null=True, verbose_name='وضعیت مدرک')),
                ('clearedStatus', models.BooleanField(blank=True, default=False, null=True, verbose_name='وضعیت تسویه')),
                ('doc_1', models.TextField(blank=True, null=True)),
                ('doc_2', models.TextField(blank=True, null=True)),
                ('doc_3', models.TextField(blank=True, null=True)),
                ('doc_4', models.TextField(blank=True, null=True)),
                ('doc_5', models.TextField(blank=True, null=True)),
                ('doc_6', models.TextField(blank=True, null=True)),
                ('doc_7', models.TextField(blank=True, null=True)),
                ('doc_8', models.TextField(blank=True, null=True)),
                ('doc_9', models.TextField(blank=True, null=True)),
                ('doc_10', models.TextField(blank=True, null=True)),
                ('doc_11', models.TextField(blank=True, null=True)),
                ('doc_12', models.TextField(blank=True, null=True)),
                ('doc_13', models.TextField(blank=True, null=True)),
                ('doc_14', models.TextField(blank=True, null=True)),
                ('doc_15', models.TextField(blank=True, null=True)),
                ('doc_16', models.TextField(blank=True, null=True)),
                ('doc_17', models.TextField(blank=True, null=True)),
                ('doc_18', models.TextField(blank=True, null=True)),
                ('doc_19', models.TextField(blank=True, null=True)),
                ('doc_20', models.TextField(blank=True, null=True)),
                ('doc_bail_1', models.TextField(blank=True, null=True)),
                ('doc_bail_2', models.TextField(blank=True, null=True)),
                ('doc_bail_3', models.TextField(blank=True, null=True)),
                ('doc_bail_4', models.TextField(blank=True, null=True)),
                ('doc_bail_5', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'قرارداد ها',
            },
        ),
    ]
