# Generated by Django 4.2 on 2023-07-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractNumber', models.CharField(blank=True, max_length=500, null=True)),
                ('employer', models.CharField(blank=True, max_length=50, null=True)),
                ('type_form', models.BooleanField(blank=True, max_length=50, null=True)),
                ('dateContract', models.DateField(blank=True, null=True)),
                ('contractPrice', models.CharField(blank=True, max_length=50, null=True)),
                ('durationContract', models.CharField(blank=True, max_length=50, null=True)),
                ('prePaidPrice', models.CharField(blank=True, max_length=50, null=True)),
                ('goodPrice', models.CharField(blank=True, max_length=50, null=True)),
                ('typeBail1', models.CharField(blank=True, max_length=50, null=True)),
                ('firstBail', models.CharField(blank=True, max_length=50, null=True)),
                ('secondBail', models.CharField(blank=True, max_length=50, null=True)),
                ('commitmentPrice', models.CharField(blank=True, max_length=50, null=True)),
                ('typeBail2', models.CharField(blank=True, max_length=50, null=True)),
                ('firstBail2', models.CharField(blank=True, max_length=50, null=True)),
                ('secondBail2', models.CharField(blank=True, max_length=50, null=True)),
                ('topicContract', models.CharField(blank=True, max_length=50, null=True)),
                ('typeContract', models.CharField(blank=True, max_length=50, null=True)),
                ('clearedDate', models.DateField(blank=True, null=True)),
                ('receivedDocument', models.BooleanField(blank=True, default=False, null=True)),
                ('clearedStatus', models.BooleanField(blank=True, default=False, null=True)),
                ('doc_1', models.TextField(blank=True, null=True)),
                ('doc_2', models.TextField(blank=True, null=True)),
                ('doc_3', models.TextField(blank=True, null=True)),
                ('doc_4', models.TextField(blank=True, null=True)),
                ('doc_5', models.TextField(blank=True, null=True)),
                ('doc_6', models.TextField(blank=True, null=True)),
                ('doc_7', models.TextField(blank=True, null=True)),
                ('doc_8', models.TextField(blank=True, null=True)),
                ('doc_9', models.TextField(blank=True, null=True)),
                ('doc_10', models.TextField(blank=True, null=True)),
                ('doc_bail_1', models.TextField(blank=True, null=True)),
                ('doc_bail_2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
