# Generated by Django 4.2.4 on 2023-09-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': 'قرارداد ها'},
        ),
        migrations.AlterField(
            model_name='document',
            name='clearedDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='dateContract',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
