# Generated by Django 4.2 on 2023-05-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentManagement', '0002_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractNumber', models.CharField(max_length=500, unique=True)),
                ('employer', models.CharField(blank=True, max_length=50, null=True)),
                ('contractor', models.CharField(blank=True, max_length=50, null=True)),
                ('dateContract', models.DateField()),
                ('contractPrice', models.BigIntegerField()),
                ('durationContract', models.CharField(max_length=50)),
                ('prePaidPrice', models.CharField(max_length=50)),
                ('goodPrice', models.CharField(max_length=50)),
                ('typeBail1', models.CharField(max_length=50)),
                ('firstBail', models.CharField(max_length=50)),
                ('secondBail', models.CharField(max_length=50)),
                ('commitmentPrice', models.CharField(max_length=50)),
                ('typeBail2', models.CharField(max_length=50)),
                ('firstBail2', models.CharField(max_length=50)),
                ('secondBail2', models.CharField(max_length=50)),
                ('topicContract', models.CharField(max_length=50)),
                ('typeContract', models.CharField(max_length=50)),
                ('clearedDatePicker', models.DateField()),
                ('receivedDocument', models.DateField()),
            ],
        ),
    ]
