# Generated by Django 4.2.7 on 2024-01-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentManagement', '0002_alter_document_options_alter_document_cleareddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='employer',
        ),
        migrations.AddField(
            model_name='document',
            name='doc_11',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_12',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_13',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_14',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_15',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_16',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_17',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_18',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_19',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_20',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_bail_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_bail_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_bail_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='document',
            name='office',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='محل کار'),
        ),
        migrations.AlterField(
            model_name='document',
            name='clearedDate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ تسویه'),
        ),
        migrations.AlterField(
            model_name='document',
            name='clearedStatus',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='وضعیت تسویه'),
        ),
        migrations.AlterField(
            model_name='document',
            name='commitmentPrice',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مبلغ تعهد انجام کار'),
        ),
        migrations.AlterField(
            model_name='document',
            name='contractNumber',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='شماره قرارداد'),
        ),
        migrations.AlterField(
            model_name='document',
            name='contractPrice',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مبلغ قرارداد'),
        ),
        migrations.AlterField(
            model_name='document',
            name='dateContract',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ قرارداد'),
        ),
        migrations.AlterField(
            model_name='document',
            name='durationContract',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مدت قرارداد'),
        ),
        migrations.AlterField(
            model_name='document',
            name='firstBail',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مشخصه ضمانت'),
        ),
        migrations.AlterField(
            model_name='document',
            name='firstBail2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مشخصه ضمانت'),
        ),
        migrations.AlterField(
            model_name='document',
            name='goodPrice',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مبلغ حسن انجام کار'),
        ),
        migrations.AlterField(
            model_name='document',
            name='prePaidPrice',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مبلغ پیش پرداخت'),
        ),
        migrations.AlterField(
            model_name='document',
            name='receivedDocument',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='وضعیت مدرک'),
        ),
        migrations.AlterField(
            model_name='document',
            name='secondBail',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مشخصه ضمانت'),
        ),
        migrations.AlterField(
            model_name='document',
            name='secondBail2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مشخصه ضمانت'),
        ),
        migrations.AlterField(
            model_name='document',
            name='topicContract',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='موضوع قرارداد'),
        ),
        migrations.AlterField(
            model_name='document',
            name='typeBail1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع ضمانت'),
        ),
        migrations.AlterField(
            model_name='document',
            name='typeBail2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع ضمانت'),
        ),
        migrations.AlterField(
            model_name='document',
            name='typeContract',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع قرارداد'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_form',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع فرم'),
        ),
    ]
