# Generated by Django 4.2 on 2023-05-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentManagement', '0006_alter_document_contractprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='clearedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='receivedDocument',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
