# Generated by Django 4.2 on 2023-05-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentManagement', '0007_alter_document_cleareddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='contractor',
        ),
    ]
