# Generated by Django 4.2 on 2023-05-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentManagement', '0008_remove_document_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type_form',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
