# Generated by Django 4.2 on 2023-05-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentManagement', '0009_document_type_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_form',
            field=models.BooleanField(blank=True, max_length=50, null=True),
        ),
    ]
