# Generated by Django 4.2 on 2023-05-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentManagement', '0013_alter_document_doc_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_1',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
