# Generated by Django 4.2 on 2023-05-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentManagement', '0017_alter_document_doc_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_bail_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_bail_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
