# Generated by Django 4.2.1 on 2023-07-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentManagement', '0020_alter_document_commitmentprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
