# Generated by Django 4.2 on 2023-07-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentManagement', '0021_document_doc_10_document_doc_5_document_doc_6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_form',
            field=models.BooleanField(blank=True, max_length=50, null=True, verbose_name="person's first name"),
        ),
    ]
