# Generated by Django 4.2 on 2023-05-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('national_id', models.CharField(max_length=50, unique=True)),
                ('sex', models.CharField(max_length=50)),
                ('office', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('approvedPrice', models.CharField(max_length=50)),
                ('commitmentPrice', models.CharField(max_length=50)),
                ('typeBail', models.CharField(max_length=50)),
                ('firstBail', models.CharField(max_length=50)),
                ('secondBail', models.CharField(max_length=50)),
                ('topicContract', models.CharField(max_length=50)),
                ('typeContract', models.CharField(max_length=50)),
                ('clearedStatus', models.BooleanField(default=False)),
                ('clearedDate', models.DateField()),
                ('receivedDocument', models.BooleanField(default=False)),
                ('Birth_certificate1', models.FileField(blank=True, null=True, upload_to='')),
                ('Birth_certificate2', models.FileField(blank=True, null=True, upload_to='')),
                ('Birth_certificate3', models.FileField(blank=True, null=True, upload_to='')),
                ('Birth_certificate4', models.FileField(blank=True, null=True, upload_to='')),
                ('front_card', models.FileField(blank=True, null=True, upload_to='')),
                ('back_card', models.FileField(blank=True, null=True, upload_to='')),
                ('driveLicense', models.FileField(blank=True, null=True, upload_to='')),
                ('bail', models.FileField(blank=True, null=True, upload_to='')),
                ('certificateMedic', models.FileField(blank=True, null=True, upload_to='')),
                ('insurance', models.FileField(blank=True, null=True, upload_to='')),
                ('police', models.FileField(blank=True, null=True, upload_to='')),
                ('retired', models.FileField(blank=True, null=True, upload_to='')),
                ('retired_card', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractNumber', models.CharField(max_length=500, unique=True)),
                ('employer', models.CharField(blank=True, max_length=50, null=True)),
                ('contractor', models.CharField(blank=True, max_length=50, null=True)),
                ('dateContract', models.DateField()),
                ('contractPrice', models.BigIntegerField()),
                ('durationContract', models.CharField(max_length=50)),
                ('prePaidPrice', models.CharField(max_length=50)),
                ('goodPrice', models.CharField(max_length=50)),
                ('typeBail1', models.CharField(max_length=50)),
                ('firstBail', models.CharField(max_length=50)),
                ('secondBail', models.CharField(max_length=50)),
                ('commitmentPrice', models.CharField(max_length=50)),
                ('typeBail2', models.CharField(max_length=50)),
                ('firstBail2', models.CharField(max_length=50)),
                ('secondBail2', models.CharField(max_length=50)),
                ('topicContract', models.CharField(max_length=50)),
                ('typeContract', models.CharField(max_length=50)),
                ('clearedDate', models.DateField()),
                ('receivedDocument', models.DateField()),
            ],
        ),
    ]
