# Generated by Django 4.2 on 2023-05-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
