# Generated by Django 4.2.3 on 2023-08-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManagement', '0003_alter_property_name_alter_property_typeproperty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='part2plate',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
