# Generated by Django 4.2 on 2023-05-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManagement', '0003_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='typePropertySelector',
            new_name='typeProperty',
        ),
        migrations.AddField(
            model_name='property',
            name='greenCard',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='property',
            name='saleFactor',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='carCard',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='gasCard',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='insurancePaper',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
