# Generated by Django 4.2 on 2023-05-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManagement', '0004_rename_typepropertyselector_property_typeproperty_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
