# Generated by Django 4.2.4 on 2023-10-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManagement', '0006_alter_person_options_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Birth_certificate1',
            field=models.TextField(blank=True, null=True, verbose_name='شناسنامه صفحه 1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Birth_certificate2',
            field=models.TextField(blank=True, null=True, verbose_name='شناسنامه صفحه 2'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Birth_certificate3',
            field=models.TextField(blank=True, null=True, verbose_name='شناسنامه صفحه 3'),
        ),
        migrations.AlterField(
            model_name='person',
            name='Birth_certificate4',
            field=models.TextField(blank=True, null=True, verbose_name='شناسنامه صفحه 4'),
        ),
        migrations.AlterField(
            model_name='person',
            name='affidavitDoc',
            field=models.TextField(blank=True, null=True, verbose_name='اقرارنامه'),
        ),
        migrations.AlterField(
            model_name='person',
            name='affidavitStatus',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='وضعیت اقرارنامه'),
        ),
        migrations.AlterField(
            model_name='person',
            name='approvedPrice',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تضمین مصوب'),
        ),
        migrations.AlterField(
            model_name='person',
            name='back_card',
            field=models.TextField(blank=True, null=True, verbose_name='کارت ملی پشت'),
        ),
        migrations.AlterField(
            model_name='person',
            name='bail',
            field=models.TextField(blank=True, null=True, verbose_name='وثیقه'),
        ),
        migrations.AlterField(
            model_name='person',
            name='caseNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پرونده'),
        ),
        migrations.AlterField(
            model_name='person',
            name='certificateMedic',
            field=models.TextField(blank=True, null=True, verbose_name='گواهی پزشکی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='certificateSecurity',
            field=models.TextField(blank=True, null=True, verbose_name='گواهی حفاظتی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='clearedDate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ تسویه'),
        ),
        migrations.AlterField(
            model_name='person',
            name='clearedStatus',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='وضعیت تسویه'),
        ),
        migrations.AlterField(
            model_name='person',
            name='commitmentPrice',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مبلغ تضمین\t'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ استخدام'),
        ),
        migrations.AlterField(
            model_name='person',
            name='degreeEducation',
            field=models.TextField(blank=True, null=True, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='driveLicense',
            field=models.TextField(blank=True, null=True, verbose_name='گواهینامه'),
        ),
        migrations.AlterField(
            model_name='person',
            name='expireDate',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تاریخ پایان قرارداد'),
        ),
        migrations.AlterField(
            model_name='person',
            name='extended',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='وضعیت تمدید'),
        ),
        migrations.AlterField(
            model_name='person',
            name='extension',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مدت تمدید'),
        ),
        migrations.AlterField(
            model_name='person',
            name='firstBail',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مشخصه اول'),
        ),
        migrations.AlterField(
            model_name='person',
            name='front_card',
            field=models.TextField(blank=True, null=True, verbose_name='کارت ملی رو'),
        ),
        migrations.AlterField(
            model_name='person',
            name='insurance',
            field=models.TextField(blank=True, null=True, verbose_name='گواهی بیمه'),
        ),
        migrations.AlterField(
            model_name='person',
            name='job',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شغل'),
        ),
        migrations.AlterField(
            model_name='person',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='office',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='محل کار'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personalPhoto',
            field=models.TextField(blank=True, null=True, verbose_name='عکس پرسنلی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='police',
            field=models.TextField(blank=True, null=True, verbose_name='گواهی پلیس'),
        ),
        migrations.AlterField(
            model_name='person',
            name='receivedDocument',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='وضعیت مدرک'),
        ),
        migrations.AlterField(
            model_name='person',
            name='retired',
            field=models.TextField(blank=True, null=True, verbose_name='حکم بازنشستگی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='retired_card',
            field=models.TextField(blank=True, null=True, verbose_name='کارت بازنشستگی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='retired_insurance',
            field=models.TextField(blank=True, null=True, verbose_name='دفترچه بیمه بازنشستگی'),
        ),
        migrations.AlterField(
            model_name='person',
            name='secondBail',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مشخصه دوم'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='person',
            name='typeBail',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='وثیقه تضمین'),
        ),
    ]
