# Generated by Django 4.2 on 2023-05-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManagement', '0007_alter_person_birth_certificate1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='clearedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='clearedStatus',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='receivedDocument',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
