# Generated by Django 4.2.7 on 2024-01-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManagement', '0007_alter_person_birth_certificate1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immovable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeEstate', models.CharField(max_length=50, null=True, verbose_name='نوع ملک')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='نام')),
                ('docNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره سند')),
                ('plate', models.CharField(blank=True, max_length=50, null=True, verbose_name='پلاک')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='آدرس')),
                ('landlord', models.CharField(blank=True, max_length=150, null=True, verbose_name='صاحب')),
                ('meter', models.CharField(blank=True, max_length=50, null=True, verbose_name='متراژ')),
                ('location', models.CharField(blank=True, max_length=20, null=True, verbose_name='محل')),
                ('madeOf', models.CharField(blank=True, max_length=4, null=True, verbose_name='سال ساخت')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات')),
                ('soldDate', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='تاریخ فروش')),
                ('buyer', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='خریدار')),
                ('soldStatus', models.BooleanField(blank=True, default=False, null=True, verbose_name='وضعیت فروش')),
                ('doc_1', models.TextField(blank=True, null=True)),
                ('doc_2', models.TextField(blank=True, null=True)),
                ('doc_3', models.TextField(blank=True, null=True)),
                ('doc_4', models.TextField(blank=True, null=True)),
                ('doc_5', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'غیر منقول',
            },
        ),
        migrations.CreateModel(
            name='Movable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeVehicle', models.CharField(max_length=50, null=True, verbose_name='نوع خودرو')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='نام')),
                ('docNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره سند')),
                ('motorNumber', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره موتور')),
                ('chassisNumber', models.CharField(blank=True, max_length=500, null=True, verbose_name='شماره شاسی')),
                ('owner', models.CharField(blank=True, max_length=50, null=True, verbose_name='صاحب')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='مدل')),
                ('madeOf', models.CharField(blank=True, max_length=4, null=True, verbose_name='سال ساخت')),
                ('part1plate', models.CharField(blank=True, max_length=2, null=True, verbose_name='چپ')),
                ('part2plate', models.CharField(blank=True, max_length=25, null=True, verbose_name='راست')),
                ('part3plate', models.CharField(blank=True, max_length=3, null=True, verbose_name='سریال')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='محل')),
                ('cityPlate', models.CharField(blank=True, max_length=10, null=True, verbose_name='شهر')),
                ('descriptionLocation', models.CharField(blank=True, max_length=500, null=True, verbose_name='محل استقرار')),
                ('paperDoc', models.CharField(blank=True, max_length=50, null=True, verbose_name='برگه سند')),
                ('insurancePaper', models.CharField(blank=True, max_length=50, null=True, verbose_name='بیمه نامه')),
                ('gasCard', models.CharField(blank=True, max_length=50, null=True, verbose_name='کارت سوخت')),
                ('carCard', models.CharField(blank=True, max_length=50, null=True, verbose_name='کارت ماشین')),
                ('description', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات')),
                ('soldDate', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='تاریخ فروش')),
                ('buyer', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='خریدار')),
                ('soldStatus', models.BooleanField(blank=True, default=False, null=True, verbose_name='وضعیت فروش')),
                ('saleFactorFile', models.TextField(blank=True, null=True)),
                ('insurancePaperFile', models.TextField(blank=True, null=True)),
                ('carCardFile', models.TextField(blank=True, null=True)),
                ('greenCardFile', models.TextField(blank=True, null=True)),
                ('gasCardFile', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'منقول',
            },
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
