# Generated by Django 4.2 on 2023-05-18 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManagement', '0008_alter_person_cleareddate_alter_person_clearedstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='topicContract',
        ),
        migrations.RemoveField(
            model_name='person',
            name='typeContract',
        ),
    ]
