# Generated by Django 4.2 on 2023-05-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManagement', '0011_remove_property_carplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cityPlate',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='part1plate',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='part2plate',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='part3plate',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
