# Generated by Django 4.2 on 2023-05-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManagement', '0014_property_type_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type_form',
            field=models.BooleanField(blank=True, max_length=50, null=True),
        ),
    ]
