# Generated by Django 4.2 on 2023-05-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManagement', '0015_alter_property_type_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='addressChassis',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
