# Generated by Django 4.2 on 2023-05-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManagement', '0016_alter_property_addresschassis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='soledStatus',
            new_name='soldStatus',
        ),
    ]
