# Generated by Django 4.2.4 on 2023-09-14 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_maintenance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name_plural': 'حالت تعمیر'},
        ),
    ]
