# Generated by Django 4.2.4 on 2023-10-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_alter_maintenance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='message_banner',
            field=models.TextField(blank=True, null=True),
        ),
    ]
