# Generated by Django 4.2.7 on 2024-01-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_maintenance_message_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='متن')),
            ],
            options={
                'verbose_name_plural': 'متن بنر',
            },
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='message_banner',
        ),
    ]
