# Generated by Django 4.2 on 2023-05-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
