# Generated by Django 4.2 on 2023-05-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0013_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
