# Generated by Django 4.2 on 2023-05-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0019_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
