# Generated by Django 4.2 on 2023-06-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0021_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='rank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
