# Generated by Django 4.2 on 2023-06-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0022_employee_rank_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
