from django.db import models


class Person(models.Model):
    type = models.CharField(verbose_name='وضعیت', max_length=50, blank=True, null=True)
    full_name = models.CharField(verbose_name='نام کامل', max_length=50, blank=False, null=True)
    date = models.CharField(verbose_name='تاریخ استخدام', max_length=50, blank=True, null=True)
    national_id = models.CharField(verbose_name='کد ملی', max_length=50, blank=True, null=True)
    sex = models.CharField(verbose_name='جنسیت', max_length=50, blank=True, null=True)
    extension = models.CharField(verbose_name='مدت تمدید', max_length=50, blank=True, null=True)
    office = models.CharField(verbose_name='محل کار', max_length=50, blank=True, null=True)
    job = models.CharField(verbose_name='شغل', max_length=50, blank=True, null=True)
    approvedPrice = models.CharField(verbose_name='تضمین مصوب', max_length=50, blank=True, null=True)
    caseNumber = models.CharField(verbose_name='شماره پرونده', max_length=50, blank=True, null=True)
    commitmentPrice = models.CharField(verbose_name='مبلغ تضمین	', max_length=50, blank=True, null=True)
    typeBail = models.CharField(verbose_name='وثیقه تضمین', max_length=50, blank=True, null=True)
    firstBail = models.CharField(verbose_name='مشخصه اول', max_length=50, blank=True, null=True)
    secondBail = models.CharField(verbose_name='مشخصه دوم', max_length=50, blank=True, null=True)
    clearedStatus = models.BooleanField(verbose_name='وضعیت تسویه', default=False, blank=True, null=True)
    affidavitStatus = models.BooleanField(verbose_name='وضعیت اقرارنامه', default=False, blank=True, null=True)
    clearedDate = models.CharField(verbose_name='تاریخ تسویه', max_length=50, blank=True, null=True)
    expireDate = models.CharField(verbose_name='تاریخ پایان قرارداد', max_length=50, blank=True, null=True)
    receivedDocument = models.BooleanField(verbose_name='وضعیت مدرک', default=False, blank=True, null=True)
    extended = models.BooleanField(verbose_name='وضعیت تمدید', default=False, blank=True, null=True)
    Birth_certificate1 = models.TextField(verbose_name='شناسنامه صفحه 1', blank=True, null=True)
    Birth_certificate2 = models.TextField(verbose_name='شناسنامه صفحه 2', blank=True, null=True)
    Birth_certificate3 = models.TextField(verbose_name='شناسنامه صفحه 3', blank=True, null=True)
    Birth_certificate4 = models.TextField(verbose_name='شناسنامه صفحه 4', blank=True, null=True)
    front_card = models.TextField(verbose_name='کارت ملی رو', blank=True, null=True)
    back_card = models.TextField(verbose_name='کارت ملی پشت', blank=True, null=True)
    driveLicense = models.TextField(verbose_name='گواهینامه', blank=True, null=True)
    bail = models.TextField(verbose_name='وثیقه', blank=True, null=True)
    certificateMedic = models.TextField(verbose_name='گواهی پزشکی', blank=True, null=True)
    insurance = models.TextField(verbose_name='گواهی بیمه', blank=True, null=True)
    police = models.TextField(verbose_name='گواهی پلیس', blank=True, null=True)
    retired = models.TextField(verbose_name='حکم بازنشستگی', blank=True, null=True)
    degreeEducation = models.TextField(verbose_name='مدرک تحصیلی', blank=True, null=True)
    personalPhoto = models.TextField(verbose_name='عکس پرسنلی', blank=True, null=True)
    certificateSecurity = models.TextField(verbose_name='گواهی حفاظتی', blank=True, null=True)
    retired_insurance = models.TextField(verbose_name='دفترچه بیمه بازنشستگی', blank=True, null=True)
    retired_card = models.TextField(verbose_name='کارت بازنشستگی', blank=True, null=True)
    affidavitDoc = models.TextField(verbose_name='اقرارنامه', blank=True, null=True)

    class Meta:
        verbose_name_plural = "اشخاص"


class Immovable(models.Model):
    typeEstate = models.CharField('نوع', max_length=50, blank=False, null=True)
    name = models.CharField('نام', max_length=50, blank=False, null=True)
    docNumber = models.CharField('شماره سند', max_length=50, blank=True, null=True)
    plate = models.CharField('پلاک', max_length=50, blank=True, null=True)
    address = models.CharField('آدرس', max_length=500, blank=True, null=True)
    landlord = models.CharField('صاحب', max_length=50, blank=True, null=True)
    meter = models.CharField('متراژ', max_length=50, blank=True, null=True)
    location = models.CharField('محل', max_length=50, blank=True, null=True)
    madeOf = models.CharField('سال ساخت', max_length=50, blank=True, null=True)
    description = models.CharField('توضیحات', default='', max_length=500, blank=True, null=True)
    soldDate = models.CharField('تاریخ فروش', default='', max_length=50, blank=True, null=True)
    buyer = models.CharField('خریدار', default='', max_length=50, blank=True, null=True)
    soldStatus = models.BooleanField('وضعیت فروش', default=False, blank=True, null=True)
    doc_1 = models.TextField(blank=True, null=True)
    doc_2 = models.TextField(blank=True, null=True)
    doc_3 = models.TextField(blank=True, null=True)
    doc_4 = models.TextField(blank=True, null=True)
    doc_5 = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name_plural = "غیر منقول"


class Movable(models.Model):
    typeVehicle = models.CharField('نوع', max_length=50, blank=False, null=True)
    name = models.CharField('نام', max_length=50, blank=False, null=True)
    docNumber = models.CharField('شماره سند', max_length=50, blank=True, null=True)
    motorNumber = models.CharField('شماره موتور', max_length=50, blank=True, null=True)
    chassisNumber = models.CharField('شماره شاسی', max_length=500, blank=True, null=True)
    owner = models.CharField('صاحب', max_length=50, blank=True, null=True)
    model = models.CharField('مدل', max_length=50, blank=True, null=True)
    madeOf = models.CharField('سال ساخت', max_length=50, blank=True, null=True)
    part1plate = models.CharField('چپ', max_length=2, blank=True, null=True)
    part2plate = models.CharField('راست', max_length=25, blank=True, null=True)
    part3plate = models.CharField('سریال', max_length=3, blank=True, null=True)
    location = models.CharField('محل', max_length=50, blank=True, null=True)
    cityPlate = models.CharField('شهر', max_length=50, blank=True, null=True)
    descriptionLocation = models.CharField('محل استقرار', max_length=500, blank=True, null=True)
    paperDoc = models.CharField('برگه سند', max_length=50, blank=True, null=True)
    insurancePaper = models.CharField('بیمه نامه', max_length=50, blank=True, null=True)
    gasCard = models.CharField('کارت سوخت', max_length=50, blank=True, null=True)
    carCard = models.CharField('کارت ماشین', max_length=50, blank=True, null=True)
    description = models.CharField('توضیحات', default='', max_length=500, blank=True, null=True)
    soldDate = models.CharField('تاریخ فروش', default='', max_length=50, blank=True, null=True)
    buyer = models.CharField('خریدار', default='', max_length=50, blank=True, null=True)
    soldStatus = models.BooleanField('وضعیت فروش', default=False, blank=True, null=True)
    saleFactorFile = models.TextField(blank=True, null=True)
    insurancePaperFile = models.TextField(blank=True, null=True)
    carCardFile = models.TextField(blank=True, null=True)
    greenCardFile = models.TextField(blank=True, null=True)
    gasCardFile = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name_plural = "منقول"
