from django.contrib import admin
from .models import *

admin.site.register(AutoIncrementProperty)
admin.site.register(AirportEquipment)
admin.site.register(SafetyEquipment)
admin.site.register(AirportVehicle)
admin.site.register(OfficeVehicle)
admin.site.register(AirportFurniture)
admin.site.register(DigitalFurniture)
admin.site.register(FacilityFurniture)
admin.site.register(OfficeFurniture)
admin.site.register(ElectronicFurniture)
admin.site.register(IndustrialTool)
admin.site.register(Airplane)
admin.site.register(NoneIndustrialTool)
admin.site.register(Benefit)
admin.site.register(SupportItem)
admin.site.register(RepairedDigitalFurniture)
admin.site.register(RepairedFacilityFurniture)
admin.site.register(RepairedOfficeFurniture)
admin.site.register(RepairedAirportFurniture)
admin.site.register(RepairedElectronicFurniture)
admin.site.register(RepairedSafetyEquipment)
admin.site.register(RepairedAirportEquipment)
admin.site.register(RepairedAirportVehicle)
admin.site.register(RepairedOfficeVehicle)
admin.site.register(RepairedIndustrialTool)
admin.site.register(RepairedAirplane)
admin.site.register(AutoIncrementFactor)
admin.site.register(Factors)
