# Generated by Django 4.2.7 on 2024-02-23 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoIncrementProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increment', models.BigIntegerField(blank=True, null=True, verbose_name='شمارنده')),
                ('inventory', models.CharField(blank=True, max_length=50, null=True, verbose_name='انبار')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام اموال')),
            ],
            options={
                'verbose_name_plural': 'شمارنده کد ثبت اموال',
            },
        ),
        migrations.CreateModel(
            name='AutoIncrementPropertyFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increment', models.BigIntegerField(blank=True, null=True, verbose_name='شمارنده')),
                ('inventory', models.CharField(blank=True, max_length=50, null=True, verbose_name='انبار')),
            ],
            options={
                'verbose_name_plural': 'شمارنده کد فاکتور',
            },
        ),
        migrations.CreateModel(
            name='FactorProperty',
            fields=[
                ('code', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد ثبت')),
                ('inventory', models.CharField(blank=True, max_length=50, null=True, verbose_name='انبار')),
                ('factor_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع فاکتور')),
                ('factor', models.TextField(blank=True, default='', null=True, verbose_name='فایل باینری فاکتور')),
                ('jsonData', models.JSONField(null=True, verbose_name='کپسول اقلام فاکتور')),
            ],
            options={
                'verbose_name_plural': 'فاکتور ها',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('code', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد ثبت')),
                ('category', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='دسته بندی')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام اموال')),
                ('property_number', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='شماره اموال')),
                ('model', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='مدل')),
                ('sub_item_type', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='نوع آیتم زیر مجموعه')),
                ('inventory', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='انبار')),
                ('dst_inventory', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='انبار مقصد')),
                ('user', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='یوزر')),
                ('using_location', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='محل مورد استفاده')),
                ('document_code', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='شناسه فاکتور')),
                ('number', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='شماره خط')),
                ('year_buy', models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='سال خرید')),
                ('phone_feature', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='ویژگی تلفن')),
                ('cpu', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='پردازنده')),
                ('gpu', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='گرافیک')),
                ('motherboard', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='مادربرد')),
                ('ram', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='رم')),
                ('power', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='پاور')),
                ('hdd', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='هارد')),
                ('case', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='کیس')),
                ('install_location', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='محل نصب')),
                ('type_furniture', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='نوع اثاث')),
                ('year_made', models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='سال ساخت')),
                ('owner', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='مالک')),
                ('part1plate', models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='چپ')),
                ('part2plate', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='راست')),
                ('part3plate', models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='سریال')),
                ('cityPlate', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='شهر')),
                ('motor', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='شماره موتور')),
                ('chassis', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='شماره شاسی')),
                ('use_for', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='مورد استفاده')),
                ('movement_description', models.TextField(blank=True, default='', max_length=50, null=True, verbose_name='شرح وضعیت انتقال')),
                ('description', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='شرح')),
                ('movement_status', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='وضعیت انتقال')),
                ('movement_message', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='پیغام انتقال')),
                ('last_handling_result', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='آخرین وضعیت بازرسی')),
                ('last_handling_date', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='آخرین تاریخ بازرسی')),
                ('yearly_handling', models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='سال بازرسی')),
                ('factorCode', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='property.factorproperty')),
            ],
            options={
                'verbose_name_plural': 'اموال',
            },
        ),
        migrations.CreateModel(
            name='RepairedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='نوع تعمیر')),
                ('description', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='شرح')),
                ('inventory', models.CharField(blank=True, max_length=50, null=True, verbose_name='انبار')),
                ('document_code', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='شناسه فاکتور')),
                ('kilometer', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='کیلومتر')),
                ('year_change', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='سال تعویض')),
                ('factorCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.factorproperty')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
            options={
                'verbose_name_plural': 'تعمیرات اموال',
            },
        ),
    ]
