# Generated by Django 4.2 on 2023-06-07 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoIncrement102',
        ),
        migrations.DeleteModel(
            name='AutoIncrement103',
        ),
        migrations.DeleteModel(
            name='AutoIncrement104',
        ),
        migrations.DeleteModel(
            name='AutoIncrement105',
        ),
        migrations.DeleteModel(
            name='AutoIncrement106',
        ),
        migrations.DeleteModel(
            name='AutoIncrement107',
        ),
        migrations.RemoveField(
            model_name='autoincrement101',
            name='airport_equipment',
        ),
        migrations.RemoveField(
            model_name='autoincrement101',
            name='airport_furniture',
        ),
        migrations.RemoveField(
            model_name='autoincrement101',
            name='airport_vehicle',
        ),
        migrations.RemoveField(
            model_name='autoincrement101',
            name='benefit',
        ),
        migrations.RemoveField(
            model_name='autoincrement101',
            name='digital_furniture',
        ),
        migrations.RemoveField(
            model_name='autoincrement101',
            name='electronic_furniture',
        ),
        migrations.RemoveField(
            model_name='autoincrement101',
            name='facility_furniture',
        ),
        migrations.RemoveField(
            model_name='autoincrement101',
            name='industrial_tools',
        ),
        migrations.RemoveField(
            model_name='autoincrement101',
            name='none_industrial_tools',
        ),
        migrations.RemoveField(
            model_name='autoincrement101',
            name='office_furniture',
        ),
        migrations.RemoveField(
            model_name='autoincrement101',
            name='office_vehicle',
        ),
        migrations.RemoveField(
            model_name='autoincrement101',
            name='safety_equipment',
        ),
        migrations.RemoveField(
            model_name='autoincrement101',
            name='support_item',
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='airport_equipment_01',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10101999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='airport_equipment_02',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10201999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='airport_equipment_03',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10301999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='airport_equipment_04',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10401999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='airport_equipment_05',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10501999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='airport_equipment_06',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10601999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='airport_equipment_07',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10701999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='airport_furniture_01',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10105999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='airport_furniture_02',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10205999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='airport_furniture_03',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10305999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='airport_furniture_04',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10405999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='airport_furniture_05',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10505999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='airport_furniture_06',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10605999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='airport_furniture_07',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10705999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='airport_vehicle_01',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10103999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='airport_vehicle_02',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10203999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='airport_vehicle_03',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10303999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='airport_vehicle_04',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10403999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='airport_vehicle_05',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10503999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='airport_vehicle_06',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10603999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='airport_vehicle_07',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10703999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='benefit_01',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(101012999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='benefit_02',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(102012999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='benefit_03',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(103012999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='benefit_04',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(104012999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='benefit_05',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(105012999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='benefit_06',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(106012999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='benefit_07',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(107012999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='digital_furniture_01',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10109999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='digital_furniture_02',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10209999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='digital_furniture_03',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10309999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='digital_furniture_04',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10409999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='digital_furniture_05',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10509999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='digital_furniture_06',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10609999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='digital_furniture_07',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10709999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='electronic_furniture_01',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10107999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='electronic_furniture_02',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10207999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='electronic_furniture_03',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10307999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='electronic_furniture_04',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10407999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='electronic_furniture_05',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10507999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='electronic_furniture_06',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10607999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='electronic_furniture_07',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10707999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='facility_furniture_01',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10108999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='facility_furniture_02',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10208999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='facility_furniture_03',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10308999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='facility_furniture_04',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10408999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='facility_furniture_05',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10508999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='facility_furniture_06',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10608999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='facility_furniture_07',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10708999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='industrial_tools_01',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(101011999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='industrial_tools_02',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(102011999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='industrial_tools_03',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(103011999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='industrial_tools_04',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(104011999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='industrial_tools_05',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(105011999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='industrial_tools_06',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(106011999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='industrial_tools_07',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(107011999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='none_industrial_tools_01',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(101010999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='none_industrial_tools_02',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(102010999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='none_industrial_tools_03',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(103010999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='none_industrial_tools_04',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(104010999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='none_industrial_tools_05',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(105010999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='none_industrial_tools_06',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(106010999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='none_industrial_tools_07',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(107010999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='office_furniture_01',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10106999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='office_furniture_02',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10206999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='office_furniture_03',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10306999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='office_furniture_04',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10406999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='office_furniture_05',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10506999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='office_furniture_06',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10606999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='office_furniture_07',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10706999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='office_vehicle_01',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10104999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='office_vehicle_02',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10204999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='office_vehicle_03',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10304999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='office_vehicle_04',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10404999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='office_vehicle_05',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10504999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='office_vehicle_06',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10604999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='office_vehicle_07',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10704999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='safety_equipment_01',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10102999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='safety_equipment_02',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10202999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='safety_equipment_03',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10302999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='safety_equipment_04',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10402999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='safety_equipment_05',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10502999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='safety_equipment_06',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10602999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='safety_equipment_07',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10702999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='support_item_01',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(101013999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='support_item_02',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(102013999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='support_item_03',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(103013999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='support_item_04',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(104013999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='support_item_05',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(105013999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='support_item_06',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(106013999)]),
        ),
        migrations.AddField(
            model_name='autoincrement101',
            name='support_item_07',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(107013999)]),
        ),
    ]
