# Generated by Django 4.2 on 2023-06-07 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_delete_autoincrement102_delete_autoincrement103_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutoIncrement101',
            new_name='AutoIncrementProperty',
        ),
    ]
