# Generated by Django 4.2.7 on 2024-01-30 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_airplane_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoIncrementPropertyFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increment', models.BigIntegerField(blank=True, null=True, verbose_name='شمارنده')),
                ('inventory', models.CharField(blank=True, max_length=50, null=True, verbose_name='انبار')),
            ],
            options={
                'verbose_name_plural': 'شمارنده کد فاکتور',
            },
        ),
        migrations.CreateModel(
            name='FactorProperty',
            fields=[
                ('code', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد ثبت')),
                ('inventory', models.CharField(blank=True, max_length=50, null=True, verbose_name='انبار')),
                ('factor_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع فاکتور')),
                ('factor', models.TextField(blank=True, default='', null=True, verbose_name='فایل باینری فاکتور')),
                ('jsonData', models.JSONField(null=True, verbose_name='کپسول اقلام فاکتور')),
            ],
            options={
                'verbose_name_plural': 'فاکتور ها',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('code', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='کد ثبت')),
                ('category', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='دسته بندی')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام اموال')),
                ('property_number', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='شماره اموال')),
                ('model', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='مدل')),
                ('sub_item_type', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='نوع آیتم زیر مجموعه')),
                ('inventory', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='انبار')),
                ('dst_inventory', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='انبار مقصد')),
                ('user', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='یوزر')),
                ('using_location', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='محل مورد استفاده')),
                ('document_code', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='شناسه فاکتور')),
                ('number', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='شماره خط')),
                ('year_buy', models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='سال خرید')),
                ('phone_feature', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='ویژگی تلفن')),
                ('cpu', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='پردازنده')),
                ('motherboard', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='مادربرد')),
                ('ram', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='رم')),
                ('power', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='پاور')),
                ('hdd', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='هارد')),
                ('case', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='کیس')),
                ('install_location', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='محل نصب')),
                ('type_furniture', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='نوع اثاث')),
                ('year_made', models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='سال ساخت')),
                ('owner', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='مالک')),
                ('part1plate', models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='چپ')),
                ('part2plate', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='راست')),
                ('part3plate', models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='سریال')),
                ('cityPlate', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='شهر')),
                ('motor', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='شماره موتور')),
                ('chassis', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='شماره شاسی')),
                ('use_for', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='مورد استفاده')),
                ('movement_description', models.TextField(blank=True, default='', max_length=50, null=True, verbose_name='شرح وضعیت انتقال')),
                ('description', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='شرح')),
                ('movement_status', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='وضعیت انتقال')),
                ('movement_message', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='پیغام انتقال')),
                ('last_handling_result', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='آخرین وضعیت بازرسی')),
                ('last_handling_date', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='آخرین تاریخ بازرسی')),
                ('yearly_handling', models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='سال بازرسی')),
                ('factorCode', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='property.factorproperty')),
            ],
            options={
                'verbose_name_plural': 'اموال',
            },
        ),
        migrations.CreateModel(
            name='RepairedProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='نوع تعمیر')),
                ('description', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='شرح')),
                ('inventory', models.CharField(blank=True, max_length=50, null=True, verbose_name='انبار')),
                ('document_code', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='شناسه فاکتور')),
                ('kilometer', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='کیلومتر')),
                ('year_change', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='سال تعویض')),
                ('factorCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.factorproperty')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
            options={
                'verbose_name_plural': 'تعمیرات اموال',
            },
        ),
        migrations.DeleteModel(
            name='AutoIncrementFactor',
        ),
        migrations.DeleteModel(
            name='Benefit',
        ),
        migrations.DeleteModel(
            name='Factors',
        ),
        migrations.DeleteModel(
            name='NoneIndustrialTool',
        ),
        migrations.RemoveField(
            model_name='repairedairplane',
            name='airplane',
        ),
        migrations.RemoveField(
            model_name='repairedairportequipment',
            name='airport_equipment',
        ),
        migrations.RemoveField(
            model_name='repairedairportfurniture',
            name='airport_furniture',
        ),
        migrations.RemoveField(
            model_name='repairedairportvehicle',
            name='airport_vehicle',
        ),
        migrations.RemoveField(
            model_name='repaireddigitalfurniture',
            name='digital_furniture',
        ),
        migrations.RemoveField(
            model_name='repairedelectronicfurniture',
            name='electronic_furniture',
        ),
        migrations.RemoveField(
            model_name='repairedfacilityfurniture',
            name='facility_furniture',
        ),
        migrations.RemoveField(
            model_name='repairedindustrialtool',
            name='industrial_tool',
        ),
        migrations.RemoveField(
            model_name='repairedofficefurniture',
            name='office_furniture',
        ),
        migrations.RemoveField(
            model_name='repairedofficevehicle',
            name='office_vehicle',
        ),
        migrations.RemoveField(
            model_name='repairedsafetyequipment',
            name='safety_equipment',
        ),
        migrations.DeleteModel(
            name='SupportItem',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airplane_01',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airplane_02',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airplane_03',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airplane_04',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airplane_05',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airplane_06',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airplane_07',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airport_equipment_01',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airport_equipment_02',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airport_equipment_03',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airport_equipment_04',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airport_equipment_05',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airport_equipment_06',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airport_equipment_07',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airport_furniture_01',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airport_furniture_02',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airport_furniture_03',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airport_furniture_04',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airport_furniture_05',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airport_furniture_06',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airport_furniture_07',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airport_vehicle_01',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airport_vehicle_02',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airport_vehicle_03',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airport_vehicle_04',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airport_vehicle_05',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airport_vehicle_06',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='airport_vehicle_07',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='benefit_01',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='benefit_02',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='benefit_03',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='benefit_04',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='benefit_05',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='benefit_06',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='benefit_07',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='digital_furniture_01',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='digital_furniture_02',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='digital_furniture_03',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='digital_furniture_04',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='digital_furniture_05',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='digital_furniture_06',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='digital_furniture_07',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='electronic_furniture_01',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='electronic_furniture_02',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='electronic_furniture_03',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='electronic_furniture_04',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='electronic_furniture_05',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='electronic_furniture_06',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='electronic_furniture_07',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='facility_furniture_01',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='facility_furniture_02',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='facility_furniture_03',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='facility_furniture_04',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='facility_furniture_05',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='facility_furniture_06',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='facility_furniture_07',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='industrial_tools_01',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='industrial_tools_02',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='industrial_tools_03',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='industrial_tools_04',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='industrial_tools_05',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='industrial_tools_06',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='industrial_tools_07',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='none_industrial_tools_01',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='none_industrial_tools_02',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='none_industrial_tools_03',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='none_industrial_tools_04',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='none_industrial_tools_05',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='none_industrial_tools_06',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='none_industrial_tools_07',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='office_furniture_01',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='office_furniture_02',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='office_furniture_03',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='office_furniture_04',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='office_furniture_05',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='office_furniture_06',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='office_furniture_07',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='office_vehicle_01',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='office_vehicle_02',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='office_vehicle_03',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='office_vehicle_04',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='office_vehicle_05',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='office_vehicle_06',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='office_vehicle_07',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='safety_equipment_01',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='safety_equipment_02',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='safety_equipment_03',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='safety_equipment_04',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='safety_equipment_05',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='safety_equipment_06',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='safety_equipment_07',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='support_item_01',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='support_item_02',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='support_item_03',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='support_item_04',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='support_item_05',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='support_item_06',
        ),
        migrations.RemoveField(
            model_name='autoincrementproperty',
            name='support_item_07',
        ),
        migrations.AddField(
            model_name='autoincrementproperty',
            name='increment',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='شمارنده'),
        ),
        migrations.AddField(
            model_name='autoincrementproperty',
            name='inventory',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='انبار'),
        ),
        migrations.AddField(
            model_name='autoincrementproperty',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام اموال'),
        ),
        migrations.DeleteModel(
            name='Airplane',
        ),
        migrations.DeleteModel(
            name='AirportEquipment',
        ),
        migrations.DeleteModel(
            name='AirportFurniture',
        ),
        migrations.DeleteModel(
            name='AirportVehicle',
        ),
        migrations.DeleteModel(
            name='DigitalFurniture',
        ),
        migrations.DeleteModel(
            name='ElectronicFurniture',
        ),
        migrations.DeleteModel(
            name='FacilityFurniture',
        ),
        migrations.DeleteModel(
            name='IndustrialTool',
        ),
        migrations.DeleteModel(
            name='OfficeFurniture',
        ),
        migrations.DeleteModel(
            name='OfficeVehicle',
        ),
        migrations.DeleteModel(
            name='RepairedAirplane',
        ),
        migrations.DeleteModel(
            name='RepairedAirportEquipment',
        ),
        migrations.DeleteModel(
            name='RepairedAirportFurniture',
        ),
        migrations.DeleteModel(
            name='RepairedAirportVehicle',
        ),
        migrations.DeleteModel(
            name='RepairedDigitalFurniture',
        ),
        migrations.DeleteModel(
            name='RepairedElectronicFurniture',
        ),
        migrations.DeleteModel(
            name='RepairedFacilityFurniture',
        ),
        migrations.DeleteModel(
            name='RepairedIndustrialTool',
        ),
        migrations.DeleteModel(
            name='RepairedOfficeFurniture',
        ),
        migrations.DeleteModel(
            name='RepairedOfficeVehicle',
        ),
        migrations.DeleteModel(
            name='RepairedSafetyEquipment',
        ),
        migrations.DeleteModel(
            name='SafetyEquipment',
        ),
    ]
