# Generated by Django 4.2 on 2023-06-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_remove_supportitem_repaired_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='safetyequipment',
            old_name='owner',
            new_name='use_for',
        ),
    ]
