# Generated by Django 4.2 on 2023-06-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_rename_plate_airportvehicle_plate1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportequipment',
            name='movement_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='airportfurniture',
            name='movement_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='airportvehicle',
            name='movement_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='digitalfurniture',
            name='movement_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='electronicfurniture',
            name='movement_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facilityfurniture',
            name='movement_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrialtool',
            name='movement_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='noneindustrialtool',
            name='movement_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='officefurniture',
            name='movement_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='officevehicle',
            name='movement_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='safetyequipment',
            name='movement_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supportitem',
            name='movement_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
