# Generated by Django 4.2 on 2023-06-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_airportequipment_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportequipment',
            name='sign_received',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='airportfurniture',
            name='sign_received',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='airportvehicle',
            name='sign_received',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='digitalfurniture',
            name='sign_received',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='electronicfurniture',
            name='sign_received',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='facilityfurniture',
            name='sign_received',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='industrialtool',
            name='sign_received',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='noneindustrialtool',
            name='sign_received',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='officefurniture',
            name='sign_received',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='officevehicle',
            name='sign_received',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='safetyequipment',
            name='sign_received',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportitem',
            name='sign_received',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
