# Generated by Django 4.2.1 on 2023-07-20 15:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_airportequipment_property_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('code', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('property_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('year_made', models.IntegerField(blank=True, null=True)),
                ('inventory', models.CharField(blank=True, max_length=50, null=True)),
                ('dst_inventory', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('install_location', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.CharField(blank=True, max_length=50, null=True)),
                ('type_register', models.CharField(blank=True, max_length=50, null=True)),
                ('repaired_status', models.BooleanField(blank=True, null=True)),
                ('repaired_type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('plate1', models.CharField(blank=True, max_length=50, null=True)),
                ('plate2', models.CharField(blank=True, max_length=50, null=True)),
                ('plate3', models.CharField(blank=True, max_length=50, null=True)),
                ('plate4', models.CharField(blank=True, max_length=50, null=True)),
                ('motor', models.CharField(blank=True, max_length=50, null=True)),
                ('chassis', models.CharField(blank=True, max_length=50, null=True)),
                ('kilometer', models.BigIntegerField(blank=True, null=True)),
                ('year_changed', models.IntegerField(blank=True, null=True)),
                ('movement_status', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.CharField(blank=True, max_length=50, null=True)),
                ('sign_received', models.TextField(blank=True, max_length=500, null=True)),
                ('last_handling_result', models.TextField(blank=True, max_length=500, null=True)),
                ('last_handling_date', models.DateField(blank=True, null=True)),
                ('yearly_handling', models.CharField(blank=True, max_length=4, null=True)),
                ('document_code', models.CharField(blank=True, max_length=50, null=True)),
                ('systemID', models.BigIntegerField(blank=True, null=True)),
                ('factor', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutoIncrementFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemID', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='airportequipment',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='airportequipment',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airportequipment',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airportfurniture',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='airportfurniture',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airportfurniture',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airportvehicle',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='airportvehicle',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airportvehicle',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autoincrementproperty',
            name='airplane_01',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(101014999)]),
        ),
        migrations.AddField(
            model_name='autoincrementproperty',
            name='airplane_02',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(102014999)]),
        ),
        migrations.AddField(
            model_name='autoincrementproperty',
            name='airplane_03',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(103014999)]),
        ),
        migrations.AddField(
            model_name='autoincrementproperty',
            name='airplane_04',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(104014999)]),
        ),
        migrations.AddField(
            model_name='autoincrementproperty',
            name='airplane_05',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(105014999)]),
        ),
        migrations.AddField(
            model_name='autoincrementproperty',
            name='airplane_06',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(106014999)]),
        ),
        migrations.AddField(
            model_name='autoincrementproperty',
            name='airplane_07',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(107014999)]),
        ),
        migrations.AddField(
            model_name='benefit',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='benefit',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='benefit',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalfurniture',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='digitalfurniture',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalfurniture',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electronicfurniture',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='electronicfurniture',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electronicfurniture',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilityfurniture',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facilityfurniture',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilityfurniture',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='industrialtool',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='industrialtool',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='industrialtool',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noneindustrialtool',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='noneindustrialtool',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noneindustrialtool',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officefurniture',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='officefurniture',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officefurniture',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officevehicle',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='officevehicle',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officevehicle',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairedairportequipment',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='repairedairportequipment',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairedairportequipment',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairedairportfurniture',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='repairedairportfurniture',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairedairportfurniture',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairedairportvehicle',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='repairedairportvehicle',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairedairportvehicle',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repaireddigitalfurniture',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='repaireddigitalfurniture',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repaireddigitalfurniture',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairedelectronicfurniture',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='repairedelectronicfurniture',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairedelectronicfurniture',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairedfacilityfurniture',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='repairedfacilityfurniture',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairedfacilityfurniture',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairedindustrialtool',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='repairedindustrialtool',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairedindustrialtool',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairedofficefurniture',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='repairedofficefurniture',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairedofficefurniture',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairedofficevehicle',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='repairedofficevehicle',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairedofficevehicle',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairedsafetyequipment',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='repairedsafetyequipment',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairedsafetyequipment',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safetyequipment',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='safetyequipment',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safetyequipment',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportitem',
            name='document_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supportitem',
            name='factor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportitem',
            name='systemID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RepairedAirplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('repaired_type', models.CharField(blank=True, max_length=50, null=True)),
                ('kilometer', models.BigIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('year_changed', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('document_code', models.CharField(blank=True, max_length=50, null=True)),
                ('systemID', models.BigIntegerField(blank=True, null=True)),
                ('factor', models.TextField(blank=True, null=True)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.airplane')),
            ],
        ),
    ]
