# Generated by Django 4.2.1 on 2023-07-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_airplane_autoincrementfactor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.BigIntegerField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('document_code', models.CharField(blank=True, max_length=50, null=True)),
                ('systemID', models.BigIntegerField(blank=True, null=True)),
                ('factor', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
