# Generated by Django 4.2.1 on 2023-07-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_rename_systemid_autoincrementfactor_systemid_01_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factors',
            name='systemID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
