# Generated by Django 4.2.1 on 2023-07-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_alter_factors_systemid'),
    ]

    operations = [
        migrations.AddField(
            model_name='factors',
            name='inventory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
